# -*- coding: utf-8 -*-
"""webScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQFIQKZap6WTTuNskukZsk03nVWQ-_2Z
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
WebPage=requests.get('https://www.espncricinfo.com/series/indian-premier-league-2024-1410320/most-valuable-players', headers = headers).text

Soup = BeautifulSoup(WebPage,'lxml')

print(Soup.prettify())

# Assuming 'Soup' is your BeautifulSoup object
rows = Soup.find_all('tr')

# Extract the header
header = [th.text for th in rows[0].find_all('th') ]

# Extract the data
data = []
for row in rows[1:183]:  # Adjust the range as needed
    data.append([td.text for td in row.find_all('td')])

# Create a DataFrame
df = pd.DataFrame(data, columns=header)

# Print the DataFrame
print(df)

# Assuming 'df' is your DataFrame
df['Wkts'] = df['Wkts'].replace('-', 0)

if not pd.api.types.is_numeric_dtype(df['Wkts']):
   df['Wkts'] = pd.to_numeric(df['Wkts'])


print(df)

pd.set_option('display.max_rows', 182)

print(df)

# Assuming 'df' is your DataFrame

# Take input from the user for the team names
TeamA = input("Enter the name of Team A: ")
TeamB = input("Enter the name of Team B: ")

# Filter rows based on the teams 'TeamA' and 'TeamB'
filtered_df = df[df['Team'].isin([TeamA, TeamB])]

# Print the new table
print("Players from Team A and Team B:")
print(filtered_df)

filtered_df.head(11)

